### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by amir-reza85** [pirateksh/codeforces-upsolving-helper#1]
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by pirateksh** [comment]
Could you please tell the Codeforces handle that you Entered @amir-reza85 ?. I will look into it.

**Comment by samsoldeinstein** [comment]
error occured while searching handle "errichto"

**Comment by amir-reza85** [comment]
Amir_Reza
my own codeforces profile

**Comment by amir-reza85** [comment]
Here is video : 
https://filebin.net/eq0wude0q250mk1y/20200709_220450.mp4?t=2g27244w

**Comment by pirateksh** [comment]
**FIXED**. This was due to an **acmsguru** problem which was not being handled. Now you can see it at the end in **Other(s)** section.
Screenshot is attached. Thankyou for bringing this into notice.
![amir](https://user-images.githubusercontent.com/46218536/87086181-d1b8ac80-c24e-11ea-92fa-6e618a5ccf9a.png)

**Comment by amir-reza85** [comment]
Really Thanks
