### ISSUE TITLE
getting internal error

### ISSUE THREAD

**Issue by albexl** [pirateksh/codeforces-upsolving-helper#2]
when I introduce my handle @albeXL, it keeps giving me internal error verdict

**Comment by pirateksh** [comment]
Hey @albexl ! When I checked with your Codeforces Handle **albexl** the website worked fine. So, my guess is that probably you were getting **Internal Server Error** because when you entered your handle, one of your submissions on Codeforces was still **in queue** which was not being handled correctly in my website. I have **FIXED** that now and even if any submission is in queue, Codeforces Upsolving Helper will work fine. Thankyou for bringing this into notice.
PS: Another possible reason for Internal Server Error is that probably Codeforces Server was down.
![alb](https://user-images.githubusercontent.com/46218536/87238677-578d5100-c423-11ea-988b-6a09fdee6479.png)
