### ISSUE TITLE
Team Mode

### ISSUE THREAD

**Issue by amir-reza85** [pirateksh/codeforces-upsolving-helper#3]
I entered : 
`tourist,petr,vovuh,Mifafaovo,Um_nik`
and get interal server error 

also you Example dont work : 
`tourist,petr,vovuh`
and 
`tourist, petr, vovuh`
Please help

**Comment by amir-reza85** [comment]
:|

**Comment by pirateksh** [comment]
**FIXED**.
This was because these guys Do Not have any Problems in the **Impossible Category**. So the length of list having Impossible Problems was empty and still the code was trying to get 10 random problems from an empty list which was causing Internal Server Error.
Thankyou for bringing this into notice.
![Screenshot from 2020-07-22 15-21-30](https://user-images.githubusercontent.com/46218536/88162626-30a6fa00-cc2f-11ea-8de1-65954dcd5483.png)

**Comment by amir-reza85** [comment]
Thanks
