### ISSUE TITLE
Site is not hosted NOW. [Application Error]

### ISSUE THREAD

**Issue by akhilsharmaa** [pirateksh/codeforces-upsolving-helper#9]

**Comment by pirateksh** [comment]
Hey, yes. The website was hosted on Heroku and it has stopped providing free tier services, i.e. we cannot host apps for free now.

Unfortunately, currently I am busy with my work so I am not actively maintaining this.

Will try to find some other place to host it but no promises.

Meanwhile you can clone it and run the app locally so that you can continue using it.

Apologies for the inconvenience.
